// ΠΑΡΤΙΔΑ 8α — Τα 8 κέικ, ξαναγραμμένα στο επίπεδο των υπόλοιπων συνταγών
// Μεταφορά από την απρόσιτη ενότητα SWEETS στο MEALS (cats:['desserts']).
// Οι φωτογραφίες υπάρχουν ήδη — δες τις εγγραφές MEAL_IMAGES στο τέλος του αρχείου.

  keik_sokolatas:{ing_en:["Flour 250 g", "Cocoa powder 60 g", "Sugar 200 g", "Eggs 3", "Butter 150 g", "Milk 120 ml", "Baking powder 2 tsp", "Vanilla extract 1 tsp", "Salt 1 pinch"],steps_en:["Preparing the ingredients: Take the butter, eggs and milk out of the fridge 1 hour ahead. Important: cold ingredients do not emulsify and the batter splits, baking heavy and dense.", "Preparing the tin: Butter the tin and dust it with cocoa rather than flour, so no white marks show on the dark cake.", "Beating the butter: Beat the butter with the sugar for 5 full minutes, until pale and fluffy. This is where the cake gets most of its lightness.", "Adding the eggs: Add the eggs one at a time, beating well after each. If the mixture starts to curdle, add a spoonful of the flour to bring it back.", "Sifting the dry ingredients: Sift the flour, cocoa, baking powder and salt together twice. Cocoa lumps never dissolve later and leave bitter pockets.", "Combining: Fold the dry ingredients in alternately with the milk, in three additions, starting and finishing with flour.", "Important: Stop mixing the moment no dry flour is visible. Beating flour develops gluten, and gluten turns cake rubbery.", "Baking: Pour into the tin, level the surface and bake at 175°C for 45 minutes.", "Testing: Insert a skewer in the centre — it should come out with a few moist crumbs. Wet batter means it needs 5-10 minutes more.", "Cooling: Cool in the tin for 10 minutes, then turn out onto a rack so the base does not steam and go soggy."],wine_en:"A sweet red Mavrodaphne or an espresso.",plate_en:"Serve in slices dusted with icing sugar and a scoop of vanilla ice cream alongside.",en:"Chocolate Cake",n:"Κέικ σοκολάτας",e:"🍫",cats:['desserts'],cal:380,time:60,srv:10,pop:3,cost:"~4€",cps:"~0.40€",
    ing:["Αλεύρι 250 γρ.","Κακάο 60 γρ.","Ζάχαρη 200 γρ.","Αυγά 3","Βούτυρο 150 γρ.","Γάλα 120 ml","Μπέικιν πάουντερ 2 κ.γ.","Βανίλια 1 κ.γ.","Αλάτι 1 πρέζα"],
    steps:["Προετοιμασία υλικών: Βγάζουμε βούτυρο, αυγά και γάλα από το ψυγείο 1 ώρα πριν. ΣΗΜΑΝΤΙΚΟ: τα κρύα υλικά δεν γαλακτωματοποιούνται και το μείγμα κόβει, οπότε ψήνεται βαρύ και συμπαγές.","Ετοιμασία φόρμας: Βουτυρώνουμε τη φόρμα και την πασπαλίζουμε με κακάο αντί για αλεύρι, ώστε να μη φαίνονται λευκά σημάδια στο σκούρο κέικ.","Χτύπημα βουτύρου: Χτυπάμε το βούτυρο με τη ζάχαρη 5 ολόκληρα λεπτά, μέχρι να ασπρίσει και να αφρατέψει. Εδώ παίρνει το κέικ το μεγαλύτερο μέρος της ελαφρότητάς του.","Προσθήκη αυγών: Ρίχνουμε τα αυγά ένα-ένα, χτυπώντας καλά μετά από κάθε ένα. Αν το μείγμα αρχίσει να κόβει, προσθέτουμε μια κουταλιά από το αλεύρι για να επανέλθει.","Κοσκίνισμα: Κοσκινίζουμε μαζί αλεύρι, κακάο, μπέικιν και αλάτι δύο φορές. Οι σβώλοι του κακάο δεν διαλύονται μετά και αφήνουν πικρές τσέπες.","Ένωση: Ενσωματώνουμε τα στεγνά υλικά εναλλάξ με το γάλα, σε τρεις δόσεις, ξεκινώντας και τελειώνοντας με αλεύρι.","ΣΗΜΑΝΤΙΚΟ: Σταματάμε το ανακάτεμα μόλις δεν φαίνεται στεγνό αλεύρι. Το χτύπημα του αλευριού αναπτύσσει γλουτένη, και η γλουτένη κάνει το κέικ λαστιχωτό.","Ψήσιμο: Ρίχνουμε στη φόρμα, ισιώνουμε την επιφάνεια και ψήνουμε στους 175°C για 45 λεπτά.","Δοκιμή: Βάζουμε οδοντογλυφίδα στο κέντρο — πρέπει να βγει με λίγα υγρά ψίχουλα. Αν βγει με ρευστό μείγμα, θέλει 5-10 λεπτά ακόμα.","Κρύωμα: Κρυώνουμε 10 λεπτά στη φόρμα και μετά ξεφορμάρουμε σε σχάρα, ώστε η βάση να μη μουσκέψει από τον ατμό."],
    wine:"Γλυκό κόκκινο Μαυροδάφνη ή ένας εσπρέσο.",
    plate:"Σερβίρετε σε φέτες με ζάχαρη άχνη από πάνω και μια μπάλα παγωτό βανίλια δίπλα"},

  keik_lemoniou:{ing_en:["Flour 250 g", "Sugar 180 g", "Eggs 3", "Olive oil 100 ml", "Yogurt 150 g", "Lemon zest 2 lemons", "Lemon juice 80 ml", "Baking powder 2 tsp", "Icing sugar 100 g (for the glaze)"],steps_en:["Zesting the lemons: Zest the lemons before juicing them, taking only the yellow layer. Important: the white pith underneath is bitter and that bitterness carries right through the cake.", "Beating the eggs: Beat the eggs with the sugar for 5 minutes, until pale and tripled in volume.", "Adding the oil: Pour the olive oil in a thin steady stream while beating, so it emulsifies instead of floating on top.", "Adding the yogurt: Fold in the yogurt, the zest and half the lemon juice.", "Sifting: Sift the flour with the baking powder and fold it in with a spatula in three additions.", "Important: Fold, do not beat. Once flour meets liquid, every extra turn makes the crumb tougher.", "Baking: Pour into a buttered and floured tin and bake at 175°C for 40-45 minutes.", "Piercing: Straight out of the oven, pierce the hot cake all over with a skewer.", "Important: Pour the remaining lemon juice over while the cake is still hot. A hot crumb drinks the juice; a cold one lets it run off the sides.", "Glazing: Mix the icing sugar with a little lemon juice into a thick glaze and pour it over the cooled cake so it runs down the sides."],wine_en:"A Muscat or a sweet sparkling wine.",plate_en:"Serve in slices with the lemon glaze running down the sides and zest on top.",en:"Lemon Cake",n:"Κέικ λεμονιού",e:"🍋",cats:['desserts'],cal:290,time:55,srv:10,pop:2,cost:"~3.50€",cps:"~0.35€",
    ing:["Αλεύρι 250 γρ.","Ζάχαρη 180 γρ.","Αυγά 3","Ελαιόλαδο 100 ml","Γιαούρτι 150 γρ.","Λεμόνι ξύσμα 2","Λεμόνι χυμός 80 ml","Μπέικιν πάουντερ 2 κ.γ.","Ζάχαρη άχνη 100 γρ. (για το λούστρο)"],
    steps:["Ξύσμα λεμονιού: Ξύνουμε τα λεμόνια πριν τα στύψουμε, παίρνοντας μόνο την κίτρινη στρώση. ΣΗΜΑΝΤΙΚΟ: το λευκό από κάτω είναι πικρό και η πίκρα περνάει σε όλο το κέικ.","Χτύπημα αυγών: Χτυπάμε τα αυγά με τη ζάχαρη 5 λεπτά, μέχρι να ασπρίσουν και να τριπλασιαστούν σε όγκο.","Προσθήκη λαδιού: Ρίχνουμε το ελαιόλαδο σε λεπτή σταθερή ροή ενώ χτυπάμε, ώστε να γαλακτωματοποιηθεί αντί να επιπλέει.","Προσθήκη γιαουρτιού: Ενσωματώνουμε το γιαούρτι, το ξύσμα και τον μισό χυμό λεμονιού.","Κοσκίνισμα: Κοσκινίζουμε το αλεύρι με το μπέικιν και το ανακατεύουμε με σπάτουλα σε τρεις δόσεις.","ΣΗΜΑΝΤΙΚΟ: Αναδεύουμε, δεν χτυπάμε. Από τη στιγμή που το αλεύρι συναντά υγρό, κάθε επιπλέον κίνηση σκληραίνει τη ψίχα.","Ψήσιμο: Ρίχνουμε σε βουτυρωμένη και αλευρωμένη φόρμα και ψήνουμε στους 175°C για 40-45 λεπτά.","Τρύπημα: Κατευθείαν από τον φούρνο, τρυπάμε παντού το ζεστό κέικ με σουβλάκι.","ΣΗΜΑΝΤΙΚΟ: Περιχύνουμε με τον υπόλοιπο χυμό λεμονιού όσο το κέικ είναι ακόμα ζεστό. Η ζεστή ψίχα ρουφάει τον χυμό, η κρύα τον αφήνει να τρέξει στα πλάγια.","Λούστρο: Ανακατεύουμε την άχνη με λίγο χυμό λεμονιού σε πηχτό λούστρο και το περιχύνουμε στο κρύο κέικ ώστε να στάζει στις πλευρές."],
    wine:"Μοσχάτο ή αφρώδης γλυκός οίνος.",
    plate:"Σερβίρετε σε φέτες με το λούστρο λεμονιού να στάζει στις πλευρές και ξύσμα από πάνω"},

  keik_portokaliou:{ing_en:["Flour 280 g", "Sugar 200 g", "Eggs 4", "Olive oil 120 ml", "Orange juice 150 ml", "Orange zest 2 oranges", "Baking powder 2 tsp", "Vanilla extract 1 tsp", "Salt 1 pinch"],steps_en:["Preparing the oranges: Zest the oranges first, then juice them. Important: use freshly squeezed juice — bottled juice is pasteurised and has lost the aromatics that make this cake.", "Beating the eggs: Beat the eggs with the sugar for 6 minutes, until very pale and thick enough to leave a ribbon trail.", "Adding the oil: Add the olive oil slowly while beating continuously.", "Adding the juice: Fold in the orange juice and the zest gently.", "Sifting: Sift the flour with the baking powder and salt and fold it in with a spatula.", "Important: The batter will look thinner than usual — this is correct. The extra juice is what makes the cake so moist.", "Baking: Pour into a buttered tin and bake at 180°C for 45 minutes.", "Important: Do not open the oven door during the first 30 minutes. The sudden temperature drop makes the risen centre collapse.", "Testing: Test with a skewer in the centre, which should come out clean.", "Cooling: Cool for 10 minutes in the tin, then turn out and dust with icing sugar once completely cold."],wine_en:"Vin santo or an orange liqueur.",plate_en:"Serve with fresh orange slices alongside and a little zest on top.",en:"Orange Cake",n:"Κέικ πορτοκαλιού",e:"🍊",cats:['desserts'],cal:310,time:60,srv:10,pop:2,cost:"~3.50€",cps:"~0.35€",
    ing:["Αλεύρι 280 γρ.","Ζάχαρη 200 γρ.","Αυγά 4","Ελαιόλαδο 120 ml","Χυμός πορτοκαλιού 150 ml","Ξύσμα πορτοκαλιού 2","Μπέικιν πάουντερ 2 κ.γ.","Βανίλια 1 κ.γ.","Αλάτι 1 πρέζα"],
    steps:["Προετοιμασία πορτοκαλιών: Ξύνουμε πρώτα τα πορτοκάλια και μετά τα στύβουμε. ΣΗΜΑΝΤΙΚΟ: χρησιμοποιούμε φρεσκοστυμμένο χυμό — ο χυμός κουτιού είναι παστεριωμένος και έχει χάσει τα αρώματα που φτιάχνουν αυτό το κέικ.","Χτύπημα αυγών: Χτυπάμε τα αυγά με τη ζάχαρη 6 λεπτά, μέχρι να ασπρίσουν πολύ και να πήξουν τόσο ώστε να αφήνουν κορδέλα.","Προσθήκη λαδιού: Ρίχνουμε το ελαιόλαδο αργά ενώ χτυπάμε συνεχώς.","Προσθήκη χυμού: Ενσωματώνουμε απαλά τον χυμό πορτοκαλιού και το ξύσμα.","Κοσκίνισμα: Κοσκινίζουμε το αλεύρι με το μπέικιν και το αλάτι και το ανακατεύουμε με σπάτουλα.","ΣΗΜΑΝΤΙΚΟ: Το μείγμα θα φαίνεται πιο αραιό από το συνηθισμένο — έτσι πρέπει. Ο επιπλέον χυμός είναι που κάνει το κέικ τόσο ζουμερό.","Ψήσιμο: Ρίχνουμε σε βουτυρωμένη φόρμα και ψήνουμε στους 180°C για 45 λεπτά.","ΣΗΜΑΝΤΙΚΟ: Δεν ανοίγουμε την πόρτα του φούρνου τα πρώτα 30 λεπτά. Η απότομη πτώση θερμοκρασίας σωριάζει το φουσκωμένο κέντρο.","Δοκιμή: Δοκιμάζουμε με οδοντογλυφίδα στο κέντρο, που πρέπει να βγει καθαρή.","Κρύωμα: Κρυώνουμε 10 λεπτά στη φόρμα, ξεφορμάρουμε και πασπαλίζουμε με άχνη αφού κρυώσει τελείως."],
    wine:"Βιν σάντο ή λικέρ πορτοκαλιού.",
    plate:"Σερβίρετε με φέτες φρέσκου πορτοκαλιού δίπλα και λίγο ξύσμα από πάνω"},

  keik_bananas:{ing_en:["Flour 230 g", "Sugar 150 g", "Eggs 2", "Butter 100 g", "Very ripe bananas 3", "Baking soda 1 tsp", "Baking powder 1 tsp", "Cinnamon 1 tsp", "Walnuts 80 g (optional)", "Salt 1 pinch"],steps_en:["Choosing the bananas: Use bananas whose skins have turned brown and spotted. Important: underripe bananas have no aroma and not enough sugar — this is the single thing that decides the cake.", "Mashing: Mash them with a fork, leaving a few small lumps for texture rather than pureeing them smooth.", "Beating the butter: Beat the soft butter with the sugar for 4 minutes until light.", "Adding the eggs: Add the eggs one at a time, then fold in the mashed bananas.", "Sifting: Sift the flour with the baking soda, baking powder, cinnamon and salt.", "Important: The soda reacts with the acidity of the bananas and starts working immediately. From this point on, work fast and get it into the oven.", "Combining: Fold the dry ingredients in with a spatula in a few turns only, then add the walnuts.", "Baking: Pour into a lined loaf tin and bake at 175°C for 50-55 minutes.", "Checking: If the top browns too early, cover it loosely with foil and carry on baking.", "Cooling: Let it cool completely before slicing — banana cake is fragile while warm and tears apart."],wine_en:"Filter coffee or a glass of milk.",plate_en:"Serve in thick slices, slightly warm, with butter or peanut butter.",en:"Banana Cake",n:"Κέικ μπανάνας",e:"🍌",cats:['desserts'],cal:280,time:65,srv:8,pop:2,cost:"~3€",cps:"~0.35€",
    ing:["Αλεύρι 230 γρ.","Ζάχαρη 150 γρ.","Αυγά 2","Βούτυρο 100 γρ.","Μπανάνες πολύ ώριμες 3","Σόδα 1 κ.γ.","Μπέικιν πάουντερ 1 κ.γ.","Κανέλα 1 κ.γ.","Καρύδια 80 γρ. (προαιρετικά)","Αλάτι 1 πρέζα"],
    steps:["Επιλογή μπανάνας: Χρησιμοποιούμε μπανάνες που η φλούδα τους έχει μαυρίσει και γεμίσει στίγματα. ΣΗΜΑΝΤΙΚΟ: οι άγουρες μπανάνες δεν έχουν άρωμα ούτε αρκετή γλυκύτητα — αυτό μόνο κρίνει το κέικ.","Λιώσιμο: Τις λιώνουμε με πιρούνι, αφήνοντας μερικά μικρά κομματάκια για υφή αντί να τις κάνουμε λείο πουρέ.","Χτύπημα βουτύρου: Χτυπάμε το μαλακό βούτυρο με τη ζάχαρη 4 λεπτά μέχρι να αφρατέψει.","Προσθήκη αυγών: Ρίχνουμε τα αυγά ένα-ένα, και μετά ενσωματώνουμε τις λιωμένες μπανάνες.","Κοσκίνισμα: Κοσκινίζουμε το αλεύρι με τη σόδα, το μπέικιν, την κανέλα και το αλάτι.","ΣΗΜΑΝΤΙΚΟ: Η σόδα αντιδρά με την οξύτητα της μπανάνας και ξεκινά αμέσως. Από δω και πέρα δουλεύουμε γρήγορα και το βάζουμε στον φούρνο.","Ένωση: Ενσωματώνουμε τα στεγνά υλικά με σπάτουλα σε λίγες μόνο κινήσεις, και προσθέτουμε τα καρύδια.","Ψήσιμο: Ρίχνουμε σε φόρμα κέικ με λαδόκολλα και ψήνουμε στους 175°C για 50-55 λεπτά.","Έλεγχος: Αν η επιφάνεια ροδίσει νωρίς, τη σκεπάζουμε χαλαρά με αλουμινόχαρτο και συνεχίζουμε το ψήσιμο.","Κρύωμα: Το αφήνουμε να κρυώσει τελείως πριν το κόψουμε — το κέικ μπανάνας είναι εύθραυστο όσο είναι ζεστό και σκίζεται."],
    wine:"Καφές φίλτρου ή γάλα.",
    plate:"Σερβίρετε σε χοντρές φέτες, χλιαρό, με βούτυρο ή φυστικοβούτυρο"},

  keik_karotou:{ing_en:["Flour 250 g", "Sugar 200 g", "Eggs 3", "Olive oil 150 ml", "Grated carrots 300 g", "Cinnamon 2 tsp", "Nutmeg 1/2 tsp", "Baking powder 2 tsp", "Baking soda 1/2 tsp", "Walnuts 100 g", "Cream cheese 200 g (for the frosting)", "Icing sugar 100 g"],steps_en:["Grating the carrots: Grate the carrots finely, not coarsely. Important: thick shreds stay hard and crunchy in the finished cake instead of melting into it.", "Draining: Squeeze the grated carrot lightly in your hands to remove excess juice, without drying it out completely.", "Beating the eggs: Beat the eggs with the sugar for 5 minutes until pale and thickened.", "Adding the oil: Pour in the olive oil in a thin stream while beating.", "Adding the carrots: Fold in the carrots and the chopped walnuts.", "Sifting the spices: Sift the flour with the baking powder, soda, cinnamon and nutmeg, so the spices spread evenly rather than clumping.", "Combining: Fold the dry ingredients in with a spatula until just incorporated.", "Baking: Bake at 175°C for 50-55 minutes.", "Important: Let the cake cool completely before frosting. Cream cheese frosting melts on contact with a warm surface and slides straight off.", "Frosting: Beat the cream cheese with the icing sugar until smooth, spread it over the cold cake and scatter walnuts on top."],wine_en:"Earl Grey tea or a sweet wine.",plate_en:"Serve with cream cheese frosting spread over and chopped walnuts.",en:"Carrot Cake",n:"Κέικ καρότου",e:"🥕",cats:['desserts'],cal:350,time:70,srv:12,pop:3,cost:"~5€",cps:"~0.40€",
    ing:["Αλεύρι 250 γρ.","Ζάχαρη 200 γρ.","Αυγά 3","Ελαιόλαδο 150 ml","Καρότα τριμμένα 300 γρ.","Κανέλα 2 κ.γ.","Μοσχοκάρυδο 1/2 κ.γ.","Μπέικιν πάουντερ 2 κ.γ.","Σόδα 1/2 κ.γ.","Καρύδια 100 γρ.","Τυρί κρέμα 200 γρ. (για την επικάλυψη)","Ζάχαρη άχνη 100 γρ."],
    steps:["Τρίψιμο καρότων: Τρίβουμε τα καρότα ψιλά, όχι χοντρά. ΣΗΜΑΝΤΙΚΟ: οι χοντρές φέτες μένουν σκληρές και τραγανές μέσα στο έτοιμο κέικ αντί να λιώσουν μέσα του.","Στράγγισμα: Στύβουμε ελαφρά το τριμμένο καρότο στα χέρια για να φύγει το περίσσιο ζουμί, χωρίς να το στεγνώσουμε τελείως.","Χτύπημα αυγών: Χτυπάμε τα αυγά με τη ζάχαρη 5 λεπτά μέχρι να ασπρίσουν και να πήξουν.","Προσθήκη λαδιού: Ρίχνουμε το ελαιόλαδο σε λεπτή ροή ενώ χτυπάμε.","Προσθήκη καρότων: Ενσωματώνουμε τα καρότα και τα σπασμένα καρύδια.","Κοσκίνισμα μπαχαρικών: Κοσκινίζουμε το αλεύρι με το μπέικιν, τη σόδα, την κανέλα και το μοσχοκάρυδο, ώστε τα μπαχαρικά να απλωθούν ομοιόμορφα αντί να σβωλιάσουν.","Ένωση: Ενσωματώνουμε τα στεγνά υλικά με σπάτουλα μέχρι μόλις να ενωθούν.","Ψήσιμο: Ψήνουμε στους 175°C για 50-55 λεπτά.","ΣΗΜΑΝΤΙΚΟ: Αφήνουμε το κέικ να κρυώσει τελείως πριν την επικάλυψη. Η κρέμα τυριού λιώνει με το που ακουμπήσει ζεστή επιφάνεια και γλιστράει κάτω.","Επικάλυψη: Χτυπάμε το τυρί κρέμα με την άχνη μέχρι να γίνει λείο, το απλώνουμε στο κρύο κέικ και σκορπίζουμε καρύδια από πάνω."],
    wine:"Τσάι Earl Grey ή γλυκό κρασί.",
    plate:"Σερβίρετε με κρέμα τυριού απλωμένη από πάνω και τριμμένο καρύδι"},

  marble_cake:{ing_en:["Flour 280 g", "Sugar 200 g", "Eggs 4", "Butter 180 g", "Milk 100 ml", "Cocoa powder 3 tbsp", "Baking powder 2 tsp", "Vanilla extract 1 tsp", "Salt 1 pinch"],steps_en:["Preparing the ingredients: Have everything at room temperature, especially the butter and the eggs.", "Beating the butter: Beat the butter with the sugar for 5 minutes until white and fluffy.", "Adding the eggs: Add the eggs one at a time, beating well after each addition.", "Making the base batter: Sift in the flour with the baking powder and salt, folding it in alternately with the milk.", "Splitting the batter: Divide the batter into two bowls, keeping them as equal as you can.", "Making the chocolate half: Sift the cocoa into one bowl with a tablespoon of warm milk, so the mixture stays as soft as the plain one.", "Important: The two batters must be the same consistency. If one is stiffer, it will not swirl and you get separate layers instead of marbling.", "Layering: Spoon the two batters alternately into the tin, in dollops, like a chessboard.", "Important: Draw a knife through the batter in one single figure-of-eight movement. More stirring blends the colours into muddy brown and destroys the pattern.", "Baking: Bake at 175°C for 50 minutes and cool in the tin for 10 minutes before turning out."],wine_en:"A cappuccino or hot chocolate.",plate_en:"Cut into slices so the marbled pattern shows and serve on a white plate.",en:"Marble Cake",n:"Marble Cake",e:"🎂",cats:['desserts'],cal:340,time:60,srv:12,pop:2,cost:"~3.50€",cps:"~0.30€",
    ing:["Αλεύρι 280 γρ.","Ζάχαρη 200 γρ.","Αυγά 4","Βούτυρο 180 γρ.","Γάλα 100 ml","Κακάο 3 κ.σ.","Μπέικιν πάουντερ 2 κ.γ.","Βανίλια 1 κ.γ.","Αλάτι 1 πρέζα"],
    steps:["Προετοιμασία υλικών: Έχουμε τα πάντα σε θερμοκρασία δωματίου, ιδίως το βούτυρο και τα αυγά.","Χτύπημα βουτύρου: Χτυπάμε το βούτυρο με τη ζάχαρη 5 λεπτά μέχρι να ασπρίσει και να αφρατέψει.","Προσθήκη αυγών: Ρίχνουμε τα αυγά ένα-ένα, χτυπώντας καλά μετά από κάθε ένα.","Βασικό μείγμα: Κοσκινίζουμε μέσα το αλεύρι με το μπέικιν και το αλάτι, ενσωματώνοντάς το εναλλάξ με το γάλα.","Χωρισμός: Χωρίζουμε το μείγμα σε δύο μπολ, όσο πιο ίσα μπορούμε.","Σοκολατένιο μισό: Κοσκινίζουμε το κακάο στο ένα μπολ μαζί με μια κουταλιά χλιαρό γάλα, ώστε το μείγμα να μείνει το ίδιο μαλακό με το απλό.","ΣΗΜΑΝΤΙΚΟ: Τα δύο μείγματα πρέπει να έχουν την ίδια πυκνότητα. Αν το ένα είναι πιο σφιχτό, δεν στροβιλίζεται και βγαίνουν χωριστές στρώσεις αντί για μαρμάρωμα.","Στρώσεις: Ρίχνουμε τα δύο μείγματα εναλλάξ στη φόρμα, με κουταλιές, σαν σκακιέρα.","ΣΗΜΑΝΤΙΚΟ: Περνάμε ένα μαχαίρι μέσα από το μείγμα με μία μόνο κίνηση σχήματος οκτώ. Το παραπάνω ανακάτεμα ενώνει τα χρώματα σε θολό καφέ και καταστρέφει το σχέδιο.","Ψήσιμο: Ψήνουμε στους 175°C για 50 λεπτά και κρυώνουμε 10 λεπτά στη φόρμα πριν ξεφορμάρουμε."],
    wine:"Καπουτσίνο ή ζεστή σοκολάτα.",
    plate:"Κόψτε σε φέτες ώστε να φαίνεται το μαρμάρινο σχέδιο και σερβίρετε σε λευκό πιάτο"},

  keik_fraoulas:{ing_en:["Flour 230 g", "Sugar 160 g", "Eggs 2", "Butter 100 g", "Yogurt 120 g", "Strawberries 200 g", "Baking powder 2 tsp", "Vanilla extract 1 tsp", "Salt 1 pinch"],steps_en:["Preparing the strawberries: Wash and hull the strawberries and cut them into small pieces.", "Drying: Spread them on kitchen paper and dry them thoroughly. Important: wet strawberries release juice into the batter and leave a raw, gummy streak through the cake.", "Flouring the fruit: Toss the pieces in a tablespoon of the measured flour. This coating stops them sinking to the bottom during baking.", "Beating the butter: Beat the butter with the sugar for 4 minutes, then add the eggs one at a time.", "Adding the yogurt: Fold in the yogurt and the vanilla.", "Sifting: Sift the remaining flour with the baking powder and salt and fold it in with a spatula.", "Adding the fruit: Fold in the floured strawberries with two or three turns only, so they do not break up and colour the whole batter pink.", "Baking: Pour into a lined tin and bake at 175°C for 45-50 minutes.", "Important: Test with a skewer between the fruit, not through a strawberry, or the moist fruit will make you think the cake is underbaked.", "Cooling: Cool completely in the tin — this cake is very moist and breaks apart if turned out warm."],wine_en:"A sparkling rosé or champagne.",plate_en:"Serve with fresh strawberries and whipped cream on the side.",en:"Strawberry Cake",n:"Κέικ φράουλας",e:"🍓",cats:['desserts'],cal:260,time:60,srv:8,pop:2,cost:"~5€",cps:"~0.60€",
    ing:["Αλεύρι 230 γρ.","Ζάχαρη 160 γρ.","Αυγά 2","Βούτυρο 100 γρ.","Γιαούρτι 120 γρ.","Φράουλες 200 γρ.","Μπέικιν πάουντερ 2 κ.γ.","Βανίλια 1 κ.γ.","Αλάτι 1 πρέζα"],
    steps:["Προετοιμασία φράουλας: Πλένουμε και καθαρίζουμε τις φράουλες και τις κόβουμε σε μικρά κομμάτια.","Στέγνωμα: Τις απλώνουμε σε χαρτί κουζίνας και τις στεγνώνουμε καλά. ΣΗΜΑΝΤΙΚΟ: οι βρεγμένες φράουλες βγάζουν ζουμί μέσα στο μείγμα και αφήνουν μια ωμή, κολλώδη ζώνη μέσα στο κέικ.","Αλεύρωμα φρούτου: Ανακατεύουμε τα κομμάτια με μια κουταλιά από το μετρημένο αλεύρι. Αυτή η επικάλυψη τα εμποδίζει να βουλιάξουν στον πάτο κατά το ψήσιμο.","Χτύπημα βουτύρου: Χτυπάμε το βούτυρο με τη ζάχαρη 4 λεπτά, και προσθέτουμε τα αυγά ένα-ένα.","Προσθήκη γιαουρτιού: Ενσωματώνουμε το γιαούρτι και τη βανίλια.","Κοσκίνισμα: Κοσκινίζουμε το υπόλοιπο αλεύρι με το μπέικιν και το αλάτι και το ανακατεύουμε με σπάτουλα.","Προσθήκη φρούτου: Ρίχνουμε τις αλευρωμένες φράουλες με δύο-τρεις μόνο κινήσεις, ώστε να μη διαλυθούν και βάψουν ροζ όλο το μείγμα.","Ψήσιμο: Ρίχνουμε σε φόρμα με λαδόκολλα και ψήνουμε στους 175°C για 45-50 λεπτά.","ΣΗΜΑΝΤΙΚΟ: Δοκιμάζουμε με οδοντογλυφίδα ανάμεσα στα φρούτα, όχι μέσα σε φράουλα, αλλιώς το υγρό φρούτο θα σας κάνει να νομίσετε ότι το κέικ είναι άψητο.","Κρύωμα: Κρυώνουμε τελείως μέσα στη φόρμα — αυτό το κέικ είναι πολύ ζουμερό και διαλύεται αν ξεφορμαριστεί ζεστό."],
    wine:"Ροζέ αφρώδες ή σαμπάνια.",
    plate:"Σερβίρετε με φρέσκες φράουλες και σαντιγί δίπλα"},

  keik_milou_me_kanela:{ing_en:["Flour 260 g", "Sugar 180 g", "Eggs 3", "Olive oil 100 ml", "Yogurt 130 g", "Apples 2", "Cinnamon 2 tsp", "Baking powder 2 tsp", "Lemon juice 1 tbsp", "Brown sugar 2 tbsp (for the top)"],steps_en:["Preparing the apples: Peel one apple and grate it, and cut the other into small cubes. The grated one adds moisture, the cubes add texture.", "Preventing browning: Toss both at once with the lemon juice, or they will oxidise and turn grey within minutes.", "Beating the eggs: Beat the eggs with the sugar for 5 minutes until pale and thick.", "Adding the oil: Add the olive oil in a thin stream, then fold in the yogurt.", "Sifting: Sift the flour with the baking powder and the cinnamon.", "Combining: Fold the dry ingredients in with a spatula, then add the apples.", "Important: The batter is thick — do not add liquid to loosen it. The apples release plenty of juice as they bake and the cake ends up very moist.", "Topping: Pour into the tin and scatter the brown sugar mixed with a little cinnamon over the surface, which forms a light crust.", "Baking: Bake at 175°C for 50 minutes.", "Important: Test at the centre, avoiding a piece of apple. Moist fruit reads as raw batter on the skewer and leads to overbaking."],wine_en:"Mulled wine or cinnamon tea.",plate_en:"Serve warm, dusted with cinnamon and a spoonful of cream.",en:"Apple Cinnamon Cake",n:"Κέικ μήλου κανέλας",e:"🍎",cats:['desserts'],cal:320,time:65,srv:10,pop:2,cost:"~3.50€",cps:"~0.35€",
    ing:["Αλεύρι 260 γρ.","Ζάχαρη 180 γρ.","Αυγά 3","Ελαιόλαδο 100 ml","Γιαούρτι 130 γρ.","Μήλα 2","Κανέλα 2 κ.γ.","Μπέικιν πάουντερ 2 κ.γ.","Λεμόνι χυμός 1 κ.σ.","Ζάχαρη καστανή 2 κ.σ. (για την επιφάνεια)"],
    steps:["Προετοιμασία μήλων: Καθαρίζουμε το ένα μήλο και το τρίβουμε, και κόβουμε το άλλο σε μικρούς κύβους. Το τριμμένο δίνει υγρασία, οι κύβοι δίνουν υφή.","Αποφυγή μαυρίσματος: Τα ανακατεύουμε και τα δύο αμέσως με τον χυμό λεμονιού, αλλιώς οξειδώνονται και γκριζάρουν μέσα σε λίγα λεπτά.","Χτύπημα αυγών: Χτυπάμε τα αυγά με τη ζάχαρη 5 λεπτά μέχρι να ασπρίσουν και να πήξουν.","Προσθήκη λαδιού: Ρίχνουμε το ελαιόλαδο σε λεπτή ροή, και ενσωματώνουμε το γιαούρτι.","Κοσκίνισμα: Κοσκινίζουμε το αλεύρι με το μπέικιν και την κανέλα.","Ένωση: Ενσωματώνουμε τα στεγνά υλικά με σπάτουλα, και προσθέτουμε τα μήλα.","ΣΗΜΑΝΤΙΚΟ: Το μείγμα είναι πηχτό — μην προσθέσετε υγρό για να το αραιώσετε. Τα μήλα βγάζουν άφθονο ζουμί στο ψήσιμο και το κέικ βγαίνει πολύ ζουμερό.","Επιφάνεια: Ρίχνουμε στη φόρμα και πασπαλίζουμε την επιφάνεια με την καστανή ζάχαρη ανακατεμένη με λίγη κανέλα, που σχηματίζει ελαφριά κρούστα.","Ψήσιμο: Ψήνουμε στους 175°C για 50 λεπτά.","ΣΗΜΑΝΤΙΚΟ: Δοκιμάζουμε στο κέντρο αποφεύγοντας κομμάτι μήλου. Το υγρό φρούτο μοιάζει με άψητο μείγμα στην οδοντογλυφίδα και οδηγεί σε παραψήσιμο."],
    wine:"Ζεστό κρασί ή τσάι κανέλας.",
    plate:"Σερβίρετε χλιαρό με πασπάλισμα κανέλας και μια κουταλιά κρέμα"},

// ── Εγγραφές για το MEAL_IMAGES ──
// keik_sokolatas:'images/keik_sokolatas.jpg',keik_lemoniou:'images/keik_lemoniou.jpg',
// keik_portokaliou:'images/keik_portokaliou.jpg',keik_bananas:'images/keik_bananas.jpg',
// keik_karotou:'images/keik_karotou.jpg',marble_cake:'images/marble_cake.jpg',
// keik_fraoulas:'images/keik_fraoulas.jpg',keik_milou_me_kanela:'images/keik_milou_me_kanela.jpg'
