// ΠΑΡΤΙΔΑ 9 — Νησιά & Επτάνησα (7 συνταγές)
// Έτοιμο για ένθεση στο MEALS του index.html. ΔΕΝ έχει προστεθεί ακόμα.
// Εικόνες: _prepared/images-new/ (ladenia, mastelo, louza, pitaroudia,
// fava_amorgou, bianco, savoro) — όλες ελεγμένες.

  ladenia:{ing_en:["Strong flour 500 g", "Dry yeast 1 sachet (9 g)", "Lukewarm water 300 ml", "Olive oil 100 ml", "Ripe tomatoes 5", "Onions 2 large", "Dried oregano 2 tbsp", "Sugar 1 tsp", "Salt, pepper"],steps_en:["Starting the dough: Dissolve the yeast and the sugar in the lukewarm water and leave it for 10 minutes until it foams, which tells you the yeast is alive.", "Kneading: Mix the flour with salt, pour in the yeast mixture and half the oil and knead for 8-10 minutes into a soft, slightly sticky dough.", "Rising: Cover the bowl and leave the dough in a warm spot for about 1 hour, until it doubles in size.", "Preparing the vegetables: Slice the tomatoes into thin rounds and the onions into thin rings. Important: salt the tomato slices and leave them on a rack for 15 minutes, then pat them dry — their water is what turns the base soggy.", "Shaping: Spread the dough by hand into an oiled round tin, about 1.5 cm thick, pressing dimples into the surface with your fingertips.", "Topping: Scatter the onion rings first, then lay the tomato slices over them so the onion steams underneath instead of burning.", "Seasoning: Sprinkle generously with oregano, salt and pepper and pour the rest of the olive oil over the whole surface.", "Baking: Bake at 200°C for 35-40 minutes, until the edges are deep golden and the tomatoes have shrunk and caramelised.", "Resting: Let it cool for 10 minutes before cutting — ladenia is eaten warm or at room temperature, never straight from the oven."],wine_en:"A chilled island white such as Monemvasia or an unoaked Assyrtiko, which the tomato and oregano call for.",plate_en:"Serve cut into squares on a wooden board, with a little extra olive oil and oregano on top.",en:"Ladenia from Kimolos",n:"Λαδένια Κιμώλου",e:"🍅",cats:["pites","vegetables"],cal:380,time:120,srv:6,pop:2,cost:"~6€",cps:"~1.00€",
    ing:["Αλεύρι δυνατό 500 γρ.","Μαγιά ξερή 1 φακελάκι (9 γρ.)","Νερό χλιαρό 300 ml","Ελαιόλαδο 100 ml","Ντομάτες ώριμες 5","Κρεμμύδια 2 μεγάλα","Ρίγανη ξερή 2 κ.σ.","Ζάχαρη 1 κ.γ.","Αλάτι, πιπέρι"],
    steps:["Ξεκίνημα ζύμης: Διαλύουμε τη μαγιά και τη ζάχαρη στο χλιαρό νερό και αφήνουμε 10 λεπτά μέχρι να αφρίσει — έτσι ξέρουμε ότι η μαγιά ζει.","Ζύμωμα: Ανακατεύουμε το αλεύρι με το αλάτι, ρίχνουμε το μείγμα της μαγιάς και τα μισά λάδια και ζυμώνουμε 8-10 λεπτά μέχρι να γίνει μαλακή, ελαφρώς κολλώδης ζύμη.","Φούσκωμα: Σκεπάζουμε το μπολ και αφήνουμε τη ζύμη σε ζεστό σημείο περίπου 1 ώρα, μέχρι να διπλασιαστεί.","Προετοιμασία λαχανικών: Κόβουμε τις ντομάτες σε λεπτές ροδέλες και τα κρεμμύδια σε λεπτούς κρίκους. ΣΗΜΑΝΤΙΚΟ: αλατίζουμε τις ροδέλες ντομάτας και τις αφήνουμε 15 λεπτά σε σχάρα, μετά τις στεγνώνουμε — τα νερά τους είναι που μουσκεύουν τη βάση.","Άπλωμα: Απλώνουμε τη ζύμη με τα χέρια σε λαδωμένο στρογγυλό ταψί, πάχος περίπου 1.5 εκ., και πιέζουμε με τα δάχτυλα για να γίνουν λακκούβες.","Στρώσιμο: Στρώνουμε πρώτα τους κρίκους κρεμμυδιού και από πάνω τις ροδέλες ντομάτας, ώστε το κρεμμύδι να ψηθεί στον ατμό από κάτω αντί να καεί.","Καρύκευμα: Πασπαλίζουμε γενναία με ρίγανη, αλάτι και πιπέρι και περιχύνουμε με το υπόλοιπο ελαιόλαδο σε όλη την επιφάνεια.","Ψήσιμο: Ψήνουμε στους 200°C για 35-40 λεπτά, μέχρι να ροδίσουν βαθιά οι άκρες και να μαζέψουν και να καραμελώσουν οι ντομάτες.","Ξεκούραση: Αφήνουμε 10 λεπτά πριν την κόψουμε — η λαδένια τρώγεται χλιαρή ή σε θερμοκρασία δωματίου, ποτέ κατευθείαν από τον φούρνο."],
    wine:"Παγωμένο νησιώτικο λευκό, Μονεμβασιά ή Ασύρτικο χωρίς βαρέλι, που το ζητούν η ντομάτα και η ρίγανη.",
    plate:"Σερβίρετε κομμένη σε τετράγωνα πάνω σε ξύλο, με λίγο έξτρα ελαιόλαδο και ρίγανη"},

  mastelo:{ing_en:["Lamb or kid goat 1.5 kg", "Dry red wine 500 ml", "Fresh dill 2 bunches", "Olive oil 1/2 cup", "Vine shoots or 3-4 wooden skewers", "Salt, pepper"],steps_en:["Cutting the meat: Cut the lamb into large portion pieces with the bone in — the bone is what gives the sauce its body during the long bake.", "Salting: Season the pieces generously with salt and pepper and leave them for 30 minutes at room temperature.", "Lining the pot: Lay the vine shoots, or crossed wooden skewers, on the base of a clay pot. Important: the meat must not touch the bottom — it has to sit above the liquid and cook in wine steam, not boil in it.", "Layering: Arrange the meat on the shoots and tuck plenty of dill between the pieces.", "Adding the wine: Pour in the wine and the olive oil, so the liquid stays below the level of the meat.", "Sealing: Cover the pot with its lid, or with foil pressed tightly around the rim, so no steam escapes.", "Slow baking: Bake at 160°C for 3 hours. Do not open it in between — every time you lift the lid you lose the steam that is doing the work.", "Browning: Remove the lid, raise the heat to 200°C and bake for another 20 minutes until the surface takes colour.", "Serving: Let it rest for 10 minutes in the pot before serving, so the juices settle."],wine_en:"The same red you cooked with — an island Mandilaria or a Nemea Agiorgitiko.",plate_en:"Serve straight from the clay pot at the table, with fresh dill on top and bread for the wine sauce.",en:"Mastelo from Sifnos",n:"Μαστέλο Σίφνου",e:"🏺",cats:["meat"],cal:560,time:200,srv:6,pop:3,cost:"~22€",cps:"~3.70€",
    ing:["Αρνί ή κατσίκι 1.5 κιλό","Κόκκινο ξηρό κρασί 500 ml","Άνηθος φρέσκος 2 ματσάκια","Ελαιόλαδο 1/2 φλιτζάνι","Κληματόβεργες ή 3-4 ξύλινα σουβλάκια","Αλάτι, πιπέρι"],
    steps:["Κόψιμο κρέατος: Κόβουμε το αρνί σε μεγάλες μερίδες με το κόκαλο — το κόκαλο είναι που δίνει σώμα στη σάλτσα στο μακρύ ψήσιμο.","Αλάτισμα: Αλατοπιπερώνουμε γενναία τα κομμάτια και τα αφήνουμε 30 λεπτά σε θερμοκρασία δωματίου.","Στρώσιμο σκεύους: Στρώνουμε τις κληματόβεργες, ή σταυρωτά ξύλινα σουβλάκια, στον πάτο ενός πήλινου σκεύους. ΣΗΜΑΝΤΙΚΟ: το κρέας δεν πρέπει να ακουμπά τον πάτο — πρέπει να κάθεται πάνω από το υγρό και να ψήνεται στον ατμό του κρασιού, όχι να βράζει μέσα του.","Τοποθέτηση: Τακτοποιούμε το κρέας πάνω στις βέργες και χώνουμε άφθονο άνηθο ανάμεσα στα κομμάτια.","Προσθήκη κρασιού: Ρίχνουμε το κρασί και το ελαιόλαδο, ώστε το υγρό να μένει κάτω από το ύψος του κρέατος.","Σφράγισμα: Σκεπάζουμε με το καπάκι του, ή με αλουμινόχαρτο σφιχτά γύρω από το χείλος, ώστε να μη φεύγει ατμός.","Σιγανό ψήσιμο: Ψήνουμε στους 160°C για 3 ώρες. Δεν το ανοίγουμε ενδιάμεσα — κάθε φορά που σηκώνουμε το καπάκι χάνεται ο ατμός που κάνει τη δουλειά.","Ρόδισμα: Αφαιρούμε το καπάκι, ανεβάζουμε στους 200°C και ψήνουμε άλλα 20 λεπτά μέχρι να πάρει χρώμα η επιφάνεια.","Σερβίρισμα: Αφήνουμε 10 λεπτά μέσα στο σκεύος πριν σερβίρουμε, να κατακαθίσουν οι χυμοί."],
    wine:"Το ίδιο κόκκινο που μαγειρέψαμε — νησιώτικη Μανδηλαριά ή Αγιωργίτικο Νεμέας.",
    plate:"Σερβίρετε κατευθείαν από το πήλινο στο τραπέζι, με φρέσκο άνηθο από πάνω και ψωμί για τη σάλτσα"},

  louza:{ing_en:["Pork tenderloin 1 kg", "Coarse salt 200 g", "Black pepper, coarsely ground 2 tbsp", "Allspice, ground 1 tbsp", "Cinnamon, ground 1 tsp", "Dried savory or oregano 2 tbsp", "Red wine 200 ml"],steps_en:["Cleaning the meat: Trim the tenderloin of all membrane and loose fat, so the salt reaches the meat evenly everywhere.", "Salting: Bury the meat completely in coarse salt in a non-metallic container and refrigerate for 24 hours — this is what draws out the moisture.", "Rinsing: Wash off all the salt under running water and pat the meat completely dry with a cloth.", "Wine bath: Dip it briefly in the red wine and let it drain for a few minutes.", "The spice coat: Mix the pepper, allspice, cinnamon and savory and roll the meat in them, pressing so the spices stick all over.", "Wrapping: Wrap it in a clean cotton cloth or muslin and tie it with string.", "Air drying: Important: hang it in a cool, dry, well-ventilated spot at 10-15°C for 15-20 days. The temperature matters more than the time — above 18°C it spoils instead of curing.", "Checking: It is ready when it has lost about a third of its weight and feels firm all the way through.", "Serving: Slice as thinly as you can with a sharp knife, always against the grain."],wine_en:"An island white with body, or a tsipouro, which is how it is drunk on Mykonos.",plate_en:"Serve in thin slices on a wooden board with capers, rusks and a few drops of olive oil.",en:"Louza from Mykonos",n:"Λούζα Μυκόνου",e:"🥓",cats:["meat"],cal:210,time:90,srv:12,pop:2,cost:"~14€",cps:"~1.20€",
    ing:["Χοιρινό ψαρονέφρι 1 κιλό","Αλάτι χοντρό 200 γρ.","Πιπέρι μαύρο χοντροτριμμένο 2 κ.σ.","Μπαχάρι τριμμένο 1 κ.σ.","Κανέλα τριμμένη 1 κ.γ.","Θρούμπι ή ρίγανη ξερή 2 κ.σ.","Κόκκινο κρασί 200 ml"],
    steps:["Καθάρισμα κρέατος: Καθαρίζουμε το ψαρονέφρι από κάθε μεμβράνη και χαλαρό λίπος, ώστε το αλάτι να φτάνει παντού ομοιόμορφα.","Αλάτισμα: Θάβουμε εντελώς το κρέας σε χοντρό αλάτι, μέσα σε μη μεταλλικό σκεύος, και το βάζουμε στο ψυγείο για 24 ώρες — αυτό τραβά την υγρασία.","Ξέπλυμα: Ξεπλένουμε όλο το αλάτι σε τρεχούμενο νερό και στεγνώνουμε το κρέας τελείως με πανί.","Πέρασμα από κρασί: Το βουτάμε στιγμιαία στο κόκκινο κρασί και το αφήνουμε να στραγγίσει λίγα λεπτά.","Το μπαχαρικό μανδύα: Ανακατεύουμε πιπέρι, μπαχάρι, κανέλα και θρούμπι και κυλάμε μέσα το κρέας πιέζοντας, ώστε να κολλήσουν παντού.","Τύλιγμα: Το τυλίγουμε σε καθαρό βαμβακερό πανί ή τουλπάνι και το δένουμε με σπάγκο.","Στέγνωμα στον αέρα: ΣΗΜΑΝΤΙΚΟ: το κρεμάμε σε δροσερό, ξηρό και καλά αεριζόμενο μέρος, στους 10-15°C, για 15-20 ημέρες. Η θερμοκρασία μετράει περισσότερο από τον χρόνο — πάνω από 18°C χαλάει αντί να ωριμάσει.","Έλεγχος: Είναι έτοιμη όταν έχει χάσει περίπου το ένα τρίτο του βάρους της και είναι σφιχτή σε όλο της το πάχος.","Σερβίρισμα: Κόβουμε όσο πιο λεπτές φέτες γίνεται με κοφτερό μαχαίρι, πάντα κάθετα στις ίνες."],
    wine:"Νησιώτικο λευκό με σώμα, ή τσίπουρο — έτσι τη συνοδεύουν στη Μύκονο.",
    plate:"Σερβίρετε σε λεπτές φέτες πάνω σε ξύλο, με κάπαρη, παξιμάδι και λίγες σταγόνες ελαιόλαδο"},

  pitaroudia:{ing_en:["Chickpeas, dried 400 g", "Onions 2", "Fresh mint 1 bunch", "Flour 150 g", "Tomato 1 ripe", "Cumin 1 tsp", "Olive oil for frying", "Salt, pepper"],steps_en:["Soaking: Soak the chickpeas in plenty of water for 12 hours, with a pinch of baking soda, which softens their skins.", "Draining: Drain them very well and dry them on a cloth. Important: they go into the mix raw and merely soaked, never boiled — boiled chickpeas turn the mixture to paste and the fritters fall apart in the oil.", "Mincing: Pulse the chickpeas in a food processor with the onions until coarsely ground, with grains still visible.", "Mixing: Add the chopped mint, the grated tomato, the cumin, salt and pepper and mix well.", "Adding the flour: Work in the flour a little at a time, until the mixture holds together when you squeeze it in your palm.", "Resting: Chill the mixture for 30 minutes so the flour hydrates and the fritters keep their shape.", "Shaping: Form small flattened patties, about the size of a walnut, pressing them firmly.", "Frying: Fry them in plenty of hot oil over medium heat for 3-4 minutes a side, until deep golden. Hot oil seals them; lukewarm oil soaks them.", "Draining: Lift them onto kitchen paper and serve them hot, while the crust is still crisp."],wine_en:"A cool Rhodian white or an ouzo with ice, as a meze.",plate_en:"Serve hot on a platter with yogurt and lemon wedges, and fresh mint scattered over.",en:"Pitaroudia from Rhodes",n:"Πιταρούδια Ρόδου",e:"🧆",cats:["legumes","vegetables"],cal:340,time:60,srv:6,pop:2,cost:"~5€",cps:"~0.85€",
    ing:["Ρεβίθια ξερά 400 γρ.","Κρεμμύδια 2","Δυόσμος φρέσκος 1 ματσάκι","Αλεύρι 150 γρ.","Ντομάτα 1 ώριμη","Κύμινο 1 κ.γ.","Ελαιόλαδο για τηγάνισμα","Αλάτι, πιπέρι"],
    steps:["Μούλιασμα: Μουλιάζουμε τα ρεβίθια σε άφθονο νερό για 12 ώρες, με μια πρέζα σόδα που μαλακώνει τη φλούδα τους.","Στράγγισμα: Τα στραγγίζουμε πολύ καλά και τα στεγνώνουμε σε πανί. ΣΗΜΑΝΤΙΚΟ: μπαίνουν στο μείγμα ωμά και μόνο μουλιασμένα, ποτέ βρασμένα — τα βρασμένα ρεβίθια κάνουν το μείγμα πολτό και τα πιταρούδια διαλύονται στο λάδι.","Άλεσμα: Χτυπάμε τα ρεβίθια στο μούλτι μαζί με τα κρεμμύδια μέχρι να γίνουν χοντροκομμένα, με ορατούς κόκκους.","Ανάμειξη: Προσθέτουμε τον ψιλοκομμένο δυόσμο, την τριμμένη ντομάτα, το κύμινο, αλάτι και πιπέρι και ανακατεύουμε καλά.","Προσθήκη αλευριού: Ρίχνουμε το αλεύρι σταδιακά, μέχρι το μείγμα να στέκεται όταν το σφίγγουμε στην παλάμη.","Ξεκούραση: Βάζουμε το μείγμα στο ψυγείο για 30 λεπτά, ώστε να ενυδατωθεί το αλεύρι και να κρατήσουν σχήμα.","Πλάσιμο: Πλάθουμε μικρά πλακουτσωτά κεφτεδάκια, στο μέγεθος καρυδιού, πιέζοντάς τα καλά.","Τηγάνισμα: Τηγανίζουμε σε άφθονο καυτό λάδι σε μέτρια φωτιά, 3-4 λεπτά από κάθε πλευρά, μέχρι να ροδίσουν βαθιά. Το καυτό λάδι τα σφραγίζει, το χλιαρό τα ποτίζει.","Στράγγισμα: Τα βγάζουμε σε χαρτί κουζίνας και τα σερβίρουμε ζεστά, όσο η κρούστα είναι ακόμα τραγανή."],
    wine:"Δροσερό ροδίτικο λευκό ή ούζο με πάγο, ως μεζές.",
    plate:"Σερβίρετε ζεστά σε πιατέλα με γιαούρτι και φέτες λεμονιού, με φρέσκο δυόσμο από πάνω"},

  fava_amorgou:{ing_en:["Yellow split peas (fava) 500 g", "Onion 1", "Water 1.5 litres", "Olive oil 1/2 cup", "Louza or smoked pork 150 g", "Capers 2 tbsp", "Red onion 1 small", "Lemon 1", "Salt, pepper"],steps_en:["Rinsing: Rinse the split peas in cold water two or three times, until the water runs almost clear.", "Simmering: Put them in a pot with the whole onion and cold water and bring them to the boil over medium heat.", "Skimming: Important: skim off the foam that rises in the first 10 minutes carefully, otherwise the fava tastes bitter and never turns smooth.", "Cooking: Lower the heat, half cover the pot and simmer for 45-50 minutes, stirring now and then so nothing catches on the base.", "Salting: Salt only in the last 10 minutes. Salted early, the split peas stay hard no matter how long they cook.", "Blending: Remove the onion and blend with a stick blender into a smooth, thick purée, adding a little hot water if it is too stiff.", "Enriching: Stir in half the olive oil off the heat and check the seasoning — fava absorbs a surprising amount.", "The louza: Cut the louza into small pieces and sauté it briefly in a dry pan, until its fat renders and the edges crisp.", "Assembling: Spread the fava on a shallow plate, scatter the louza, the capers and the finely chopped red onion over it and finish with the rest of the oil and lemon juice."],wine_en:"An Assyrtiko from the Cyclades, whose acidity cuts through the richness of the purée.",plate_en:"Serve in a shallow bowl, swirled with the back of a spoon so the oil pools in the grooves.",en:"Fava from Amorgos with Louza",n:"Φάβα Αμοργού με λούζα",e:"🥣",cats:["legumes"],cal:420,time:70,srv:6,pop:2,cost:"~7€",cps:"~1.15€",
    ing:["Φάβα 500 γρ.","Κρεμμύδι 1","Νερό 1.5 λίτρο","Ελαιόλαδο 1/2 φλιτζάνι","Λούζα ή καπνιστό χοιρινό 150 γρ.","Κάπαρη 2 κ.σ.","Κόκκινο κρεμμύδι 1 μικρό","Λεμόνι 1","Αλάτι, πιπέρι"],
    steps:["Ξέπλυμα: Ξεπλένουμε τη φάβα σε κρύο νερό δύο-τρεις φορές, μέχρι το νερό να βγαίνει σχεδόν καθαρό.","Βράσιμο: Τη βάζουμε σε κατσαρόλα με το κρεμμύδι ολόκληρο και κρύο νερό και τη φέρνουμε σε βρασμό σε μέτρια φωτιά.","Ξάφρισμα: ΣΗΜΑΝΤΙΚΟ: ξαφρίζουμε προσεκτικά τον αφρό που ανεβαίνει τα πρώτα 10 λεπτά, αλλιώς η φάβα πικρίζει και δεν γίνεται ποτέ βελούδινη.","Μαγείρεμα: Χαμηλώνουμε τη φωτιά, σκεπάζουμε μισάνοιχτα και σιγοβράζουμε 45-50 λεπτά, ανακατεύοντας πού και πού για να μην πιάσει στον πάτο.","Αλάτισμα: Αλατίζουμε μόνο στα τελευταία 10 λεπτά. Αλατισμένη από την αρχή, η φάβα μένει σκληρή όσο κι αν βράσει.","Πολτοποίηση: Βγάζουμε το κρεμμύδι και χτυπάμε με ραβδομπλέντερ σε λείο, πηχτό πουρέ, προσθέτοντας λίγο ζεστό νερό αν σφίξει πολύ.","Εμπλουτισμός: Ρίχνουμε τα μισά λάδια εκτός φωτιάς και δοκιμάζουμε το αλάτι — η φάβα απορροφά εντυπωσιακά πολύ.","Η λούζα: Κόβουμε τη λούζα σε μικρά κομμάτια και τη σοτάρουμε στιγμιαία σε στεγνό τηγάνι, μέχρι να λιώσει το λίπος της και να τραγανίσουν οι άκρες.","Σύνθεση: Απλώνουμε τη φάβα σε ρηχό πιάτο, σκορπίζουμε τη λούζα, την κάπαρη και το ψιλοκομμένο κόκκινο κρεμμύδι και τελειώνουμε με το υπόλοιπο λάδι και χυμό λεμονιού."],
    wine:"Ασύρτικο Κυκλάδων, που με την οξύτητά του κόβει τη λιπαρότητα του πουρέ.",
    plate:"Σερβίρετε σε ρηχό μπολ, με αυλακιές από την ανάποδη του κουταλιού ώστε να μαζέψει το λάδι"},

  bianco:{ing_en:["White fish (scorpionfish, cod or grouper) 1.2 kg", "Potatoes 800 g", "Garlic 1 whole head", "Lemons 3", "Olive oil 3/4 cup", "Black pepper, coarsely ground 1 tbsp", "Fresh parsley 1 bunch", "Water 1 cup", "Salt"],steps_en:["Preparing the fish: Clean and scale the fish, cut it into thick portions and salt them lightly.", "Slicing the potatoes: Peel the potatoes and cut them into rounds about half a centimetre thick, so they cook in the same time as the fish.", "Layering the base: Spread the potato rounds over the base of a wide pot and season them with salt and plenty of coarse pepper.", "The garlic: Peel the whole head of garlic and scatter the cloves whole among the potatoes. Important: the garlic goes in whole, not crushed — it is meant to sweeten and melt into the sauce, not to sting.", "Adding the oil: Pour in the olive oil and the water and bring it to the boil over high heat.", "Cooking the potatoes: Lower the heat and simmer for 15 minutes, until the potatoes are half cooked.", "Adding the fish: Lay the fish pieces on top of the potatoes and cook for another 15 minutes without stirring — shake the pot by the handles instead, or the fish breaks up.", "The lemon: Pour in the lemon juice and cook for a final 5 minutes, so it does not lose its freshness.", "Finishing: Turn off the heat, scatter the chopped parsley over and let it stand for 10 minutes before serving."],wine_en:"A Robola from Kefalonia or a Kakotrygis from Corfu, the local answer to the lemon and the garlic.",plate_en:"Serve in a deep plate with the potatoes underneath, the fish on top and plenty of the lemon broth.",en:"Bianco from Corfu",n:"Μπιάνκο Κέρκυρας",e:"🐟",cats:["seafood"],cal:430,time:55,srv:5,pop:3,cost:"~20€",cps:"~4.00€",
    ing:["Ψάρι λευκόσαρκο (σκορπίνα, μπακαλιάρος ή ροφός) 1.2 κιλό","Πατάτες 800 γρ.","Σκόρδο 1 ολόκληρο κεφάλι","Λεμόνια 3","Ελαιόλαδο 3/4 φλιτζανιού","Πιπέρι μαύρο χοντροτριμμένο 1 κ.σ.","Μαϊντανός φρέσκος 1 ματσάκι","Νερό 1 φλιτζάνι","Αλάτι"],
    steps:["Προετοιμασία ψαριού: Καθαρίζουμε και ξελεπιάζουμε το ψάρι, το κόβουμε σε χοντρές μερίδες και το αλατίζουμε ελαφρά.","Κόψιμο πατάτας: Καθαρίζουμε τις πατάτες και τις κόβουμε σε ροδέλες μισού εκατοστού, ώστε να ψηθούν στον ίδιο χρόνο με το ψάρι.","Στρώσιμο βάσης: Απλώνουμε τις ροδέλες πατάτας στον πάτο φαρδιάς κατσαρόλας και τις αλατοπιπερώνουμε με άφθονο χοντρό πιπέρι.","Το σκόρδο: Καθαρίζουμε ολόκληρο το κεφάλι σκόρδο και σκορπίζουμε τις σκελίδες ακέραιες ανάμεσα στις πατάτες. ΣΗΜΑΝΤΙΚΟ: το σκόρδο μπαίνει ολόκληρο, όχι λιωμένο — προορίζεται να γλυκάνει και να λιώσει μέσα στη σάλτσα, όχι να τσούζει.","Προσθήκη λαδιού: Ρίχνουμε το ελαιόλαδο και το νερό και φέρνουμε σε βρασμό σε δυνατή φωτιά.","Βράσιμο πατάτας: Χαμηλώνουμε και σιγοβράζουμε 15 λεπτά, μέχρι οι πατάτες να είναι μισοψημένες.","Προσθήκη ψαριού: Τοποθετούμε τα κομμάτια ψαριού πάνω στις πατάτες και μαγειρεύουμε άλλα 15 λεπτά χωρίς να ανακατέψουμε — κουνάμε την κατσαρόλα από τα χερούλια, αλλιώς το ψάρι διαλύεται.","Το λεμόνι: Ρίχνουμε τον χυμό λεμονιού και βράζουμε ακόμα 5 λεπτά, ώστε να μη χάσει τη φρεσκάδα του.","Ολοκλήρωση: Σβήνουμε τη φωτιά, πασπαλίζουμε με ψιλοκομμένο μαϊντανό και αφήνουμε 10 λεπτά πριν σερβίρουμε."],
    wine:"Ρομπόλα Κεφαλονιάς ή Κακοτρύγης Κέρκυρας, η ντόπια απάντηση στο λεμόνι και το σκόρδο.",
    plate:"Σερβίρετε σε βαθύ πιάτο με τις πατάτες από κάτω, το ψάρι από πάνω και άφθονο λεμονάτο ζουμί"},

  savoro:{ing_en:["Small fish (red mullet, picarel or sardines) 1 kg", "Flour for coating 150 g", "Olive oil for frying", "Garlic 6 cloves", "Red wine vinegar 150 ml", "Sultanas 80 g", "Fresh rosemary 3 sprigs", "Bay leaves 2", "Salt, pepper"],steps_en:["Preparing the fish: Clean the fish, rinse it and dry it very thoroughly — wet fish spatters and does not crisp.", "Coating: Season the flour with salt and pepper and coat the fish, shaking off every bit of excess.", "Frying: Fry in plenty of hot oil until golden and crisp on both sides, then lift the fish onto kitchen paper.", "Straining the oil: Keep about half a cup of the frying oil and strain it, so no burnt flour remains in the sauce.", "The aromatics: Sauté the sliced garlic in that oil over low heat for 1 minute, just until it smells — browned garlic turns the whole savoro bitter.", "Deglazing: Pour in the vinegar, add the rosemary and the bay and let it bubble for 2-3 minutes so the sharpness burns off.", "The sultanas: Add the sultanas and simmer for another 2 minutes, until they swell and sweeten the sauce.", "Marinating: Important: arrange the fish in a non-metallic dish and pour the hot sauce over the cold fish, never the other way round — that contrast is what makes savoro set.", "Resting: Cover and refrigerate for at least 12 hours. Savoro is eaten the next day; on the first day it has no flavour yet."],wine_en:"A Kefalonian Robola or a dry rosé, both of which stand up to the vinegar.",plate_en:"Serve cold straight from the marinade, with the sultanas and rosemary spooned over, and plenty of bread.",en:"Savoro — Marinated Fish",n:"Σαβόρο",e:"🫙",cats:["seafood"],cal:390,time:45,srv:5,pop:2,cost:"~13€",cps:"~2.60€",
    ing:["Μικρά ψάρια (μπαρμπούνια, μαρίδες ή σαρδέλες) 1 κιλό","Αλεύρι για πανάρισμα 150 γρ.","Ελαιόλαδο για τηγάνισμα","Σκόρδο 6 σκελίδες","Ξίδι κόκκινου κρασιού 150 ml","Σταφίδες ξανθές 80 γρ.","Δεντρολίβανο φρέσκο 3 κλωνάρια","Δάφνη 2 φύλλα","Αλάτι, πιπέρι"],
    steps:["Προετοιμασία ψαριών: Καθαρίζουμε τα ψάρια, τα ξεπλένουμε και τα στεγνώνουμε πολύ καλά — το βρεγμένο ψάρι πετάγεται και δεν τραγανίζει.","Αλεύρωμα: Αλατοπιπερώνουμε το αλεύρι και αλευρώνουμε τα ψάρια, τινάζοντας κάθε περίσσεια.","Τηγάνισμα: Τηγανίζουμε σε άφθονο καυτό λάδι μέχρι να ροδίσουν και να τραγανίσουν και από τις δύο πλευρές, και τα βγάζουμε σε χαρτί κουζίνας.","Σούρωμα λαδιού: Κρατάμε περίπου μισό φλιτζάνι από το λάδι του τηγανίσματος και το σουρώνουμε, ώστε να μη μείνει καμένο αλεύρι μέσα στη σάλτσα.","Τα αρωματικά: Σοτάρουμε το κομμένο σκόρδο σε αυτό το λάδι σε χαμηλή φωτιά για 1 λεπτό, όσο να μυρίσει — το καβουρδισμένο σκόρδο πικρίζει όλο το σαβόρο.","Σβήσιμο: Ρίχνουμε το ξίδι, προσθέτουμε δεντρολίβανο και δάφνη και αφήνουμε να κοχλάσει 2-3 λεπτά ώστε να φύγει η μύτη του.","Οι σταφίδες: Προσθέτουμε τις σταφίδες και σιγοβράζουμε άλλα 2 λεπτά, μέχρι να φουσκώσουν και να γλυκάνουν τη σάλτσα.","Μαρινάρισμα: ΣΗΜΑΝΤΙΚΟ: τακτοποιούμε τα ψάρια σε μη μεταλλικό σκεύος και περιχύνουμε τη ζεστή σάλτσα πάνω στα κρύα ψάρια, ποτέ το αντίστροφο — αυτή η αντίθεση είναι που δένει το σαβόρο.","Ξεκούραση: Σκεπάζουμε και βάζουμε στο ψυγείο τουλάχιστον 12 ώρες. Το σαβόρο τρώγεται την επόμενη μέρα· την πρώτη δεν έχει ακόμα γεύση."],
    wine:"Ρομπόλα Κεφαλονιάς ή ξηρό ροζέ, που αντέχουν και τα δύο το ξίδι.",
    plate:"Σερβίρετε κρύο κατευθείαν από τη μαρινάδα, με τις σταφίδες και το δεντρολίβανο από πάνω και άφθονο ψωμί"},
